from tkinter import messagebox

CANT_GET_PRICE = -1
NO_BODYBUILDING = "No-Bodybuilding"
FULL_WEEK = "Full-Week"
HALF_WEEK = "Half-Week"
NO_CARDIO = "No-Cardio"
MONTHLY = "Monthly"
THREE_MONTHS = "Three Months"
SIX_MONTHS = "Six Months"
YEARLY = "Yearly"
ADMIN_MANAGER = "1"
ADMIN_NO = "0"
MALE = "Male"
FEMALE = "Female"
REGISTRATION_PHOTO_IDX = 13
MONTHLY_DISCOUNT = 0
THREE_MONTHS_DISCOUNT = 0.05
SIX_MONTHS_DISCOUNT = 0.1
YEARLY_DISCOUNT = 0.15
FULL_WEEK_COST = 200
HALF_WEEK_COST = 100
